AWSTemplateFormatVersion: 2010-09-09
Description: The CloudFormation template for the S3.

Parameters:
  S3BUCKET:
    Type: String
    Default: s3bucket #TODO: have this consistent with the other cf templates and with the Github actions 

Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Properties: 
            BucketName: !Ref S3BUCKET

Outputs:
    BucketName:
        Value: !Ref 'S3Bucket'