name: CI-Tests
on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - 'delivery/**'

env:
  AWS_DEFAULT_REGION: 'eu-central-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  dummy:
    name: dummy job
        run: echo 'Hello World'
