name: (V2) Deploy MLFlow Service Infrastructure
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: Project ID (For the name of the Prefect blocks, ...) #NOTE: It can be the CU Task ID
        required: true
        default: '34aghxe'
      service_name:
        description: Name of the service
        required: true
        default: 'mlflow-server'
      aws-region:
        description: AWS Region
        required: true
        default: 'eu-central-1'
        type: string
        
env:
  SERVICE: mlflow-server
  PROJECT_ID: ${{ github.event.inputs.project_id }}
  AWS_REGION: ${{ github.event.inputs.aws-region }}
  DOCKER_PATH: ./exp-track-mod-reg-mlflowFargate/
  ECR_REPO: ${{ github.event.inputs.project_id }}-mlflow-ecr

jobs:
  ecr-repo:
    name: Create ECR repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create new ECR repository using AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "ecr-stack-mlflow-${{ env.PROJECT_ID }}"
          template: deployment_PrefectFargate/infrastructure/ecr_repository.yml
          parameter-overrides: "ECRREPO=${{ env.ECR_REPO }}"
          no-fail-on-empty-changeset: "1"

      - name: Job is finished.
        run: echo "ECR repository built at $(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_STEP_SUMMARY


  deploy:
    name: Push service image to ECR repository
    runs-on: ubuntu-latest
    needs: ecr-repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build image and push image to ECR with latest tag
          docker build -t $ECR_REGISTRY/$ECR_REPO $DOCKER_PATH
          docker push $ECR_REGISTRY/$ECR_REPO

          # Tag image with the Git-Sha and Push again
          docker tag  $ECR_REGISTRY/$ECR_REPO $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG"

      - name: ECR image is being pushed to corresponding repository
        run: echo "ECR image ${{ steps.build-image.outputs.image }} built at $(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_STEP_SUMMARY

      - name: Deploy to ECS with AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "ecs-stack-mlflow-${{ env.PROJECT_ID }}"
          template: exp-track-mod-reg-mlflowFargate/infrastructure/ecs_cluster_mlflow_service.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: "ProjectID=${{ env.PROJECT_ID }},ServiceName=${{ env.SERVICE }},ServiceImage=${{ steps.build-image.outputs.image }}"

      - name: ECS Service Deployment finished
        run: echo "ECS Service Deployment finished at $(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_STEP_SUMMARY

      - name: Generate task definition
        run: aws ecs describe-task-definition --task-definition ${{ env.SERVICE }} --query taskDefinition > task-definition.json

      - name: Upload task definition as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ECS task definition
          path: task-definition.json

      - name: Summary
        run: echo 'AWS ECS agent successfully deployed and ready to run your flows! :rocket:' >> $GITHUB_STEP_SUMMARY