name: Dummy CD-Create Deployments
on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'develop'


env:
  AWS_DEFAULT_REGION: 'eu-central-1'
  PREFECT_VERSION: 2.1
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: ${{ env.AWS_DEFAULT_REGION}} 
          


  deploy-predicting: # Create Deployment Predicting
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
          
      - name: Python dependencies
        run: |
          pip install prefect==$PREFECT_VERSION
          pip install s3fs
          pip install .

      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY}} 
          prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL}}
          
      - name: Create Prefect Deployment
        run: |    
          prefect deployment build ./covid_PredMonitor.py:covid_prediction -n CovidPredictor -t tag_CovidPredictor --storage-block s3/$PREFECT_S3BLOCK_NAME
    
#       - name: Create Deployment Predicting
#         id: deployment-predicting
#         working-directory: '.'
#         run: |
#           cd delivery/
#           echo "Login in in Prefect Cloud..."
#           prefect cloud login -k ${{ secrets.PREFECT_API_KEY}} 
#           echo "SO FAR SO GOOD..."
        
