name: CD-Create Deployments
on:
  push:
    branches:
      - 'develop'


jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"


      # Create Deployment Predicting
      - name: Create Deployment Predicting
        id: deployment-predicting
        working-directory: 'delivery'
        run: |
          echo "Hello World"
