name: Dummy CD-Create Deployments
on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'develop'


env:
  AWS_DEFAULT_REGION: 'eu-central-1'
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: ${{ env.AWS_DEFAULT_REGION}} 

  deploy-predicting: # Create Deployment Predicting
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Create Deployment Predicting
        id: deployment-predicting
        working-directory: 'delivery'
        run: |
          echo "Login in in Prefect Cloud..."
          pipenv run prefect cloud login -k ${{ secrets.PREFECT_API_KEY}} 
          echo "SO FAR SO GOOD..."
        
